version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/github_users
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  migrate:
    build: .
    command: npm run migrate
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/github_users
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=github_users
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
